---
- hosts: webservers
  tasks:
    - name: Install Java
      import_playbook: InstallJava.yml
    - name: Install Jenkins
      import_playbook: InstallJenkins.yml
    - name: Install Apache
      import_playbook: webservers.yml
