---
- name: Install Jenkins
  hosts: controlnode
  become: true
  tasks:
    - name: Download Jenkins apt repository key
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        dest: /tmp/jenkins.io.key

    - name: Add Jenkins apt repository key
      apt_key:
        file: /tmp/jenkins.io.key
        state: present

    - name: Add Jenkins apt repository
      apt_repository:
        repo: "deb https://pkg.jenkins.io/debian-stable binary/"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java Runtime Environment
      apt:
        name: openjdk-11-jre
        state: present

    - name: Install Jenkins package
      apt:
        name: jenkins
        state: present

    - name: Install additional packages
      apt:
        name: fontconfig
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
