- hosts: webservers
  become: yes
  gather_facts: false
  vars:
    new_mysql_root_password: Pa$$w0rd
    mysqlsoftware:
      - mysql-server
      - mysql-client
  tasks:
    - name: install python, pip, etc.
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - pip 
        - python3-dev 
        - default-libmysqlclient-dev 
        - build-essential

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Install MySQL client
      apt:
        name: mysql-client
        state: present
        update_cache: yes

    - name: pip install mysqlclient
      pip:
        name: mysqlclient

    - name: Start the MySQL service
      service:
        name: mysql
        state: started

