- hosts: webservers
  become: yes
  tasks:
    - name: Include InstallJava tasks
      import_tasks: Install_Java_i.yml

    - name: Include InstallJenkins tasks
      import_tasks: Install_Jenkins_i.yml

    - name: Include webservers tasks
      import_tasks: Install_Webservers_i.yml
